### Cadastro de Usuário
POST http://localhost:5223/registro
Content-Type: application/json

{
  "Username": "Michael",
  "Password": "123Senha"
}

### Login de Usuário
POST http://localhost:5223/login
Content-Type: application/json

{
  "Username": "Michael",
  "Password": "123Senha"
}


### Criar um Fórum
POST http://localhost:5223/forum
Content-Type: application/json

{
  "Title": "Título do Fórum",
  "Description": "Descrição do Fórum",
  "IsActive": true
}


### Criar um Post em um Fórum
POST http://localhost:5223/forum/6/post
Content-Type: application/json

{
  "Title": "Título",
  "Content": "Conteúdo"
}


### Comentar em um Post
POST http://localost:5223/forum/6/post/16/comment
Content-Type: application/json

{
  "Content": "Este é um comentário no post."
}


### Enviar uma Mensagem Privada
POST http://localhost:5223/message
Content-Type: application/json


{
  "ToUserId": "b4958580-bfb3-454b-8e4f-5b92759e3408",
  "Content": "Olá, esta é uma mensagem privada."
}


### get forum
GET http://localhost:5223/forums


### get forum 6 post
GET http://localhost:5223/forum/6/posts


### get forum 6 post 16 nos comentários
GET http://localhost:5223/forum/6/post/16/comments


### get analizando forum 1
GET http://localhost:5223/analytics/forum/1


### get para procurar
GET http://localhost:5223/search


### atualizar nome usuário
PUT http://localhost:5223/usuario/atualizar-username
Content-Type: application/json

{
  "NewUsername": "B",
  "Password":"123senha"
}


### Remover um Post
DELETE http://localhost:5223/forum/6/post/16


### Remover forum
DELETE http://localhost:5000/forum/6


